// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0h_5Wc_wY7Ho2Qvl0c8bz0fDC4lL0II',
    appId: '1:126285085607:web:55109cd7eb1f24fa1d5482',
    messagingSenderId: '126285085607',
    projectId: 'codeelan-b4a49',
    authDomain: 'codeelan-b4a49.firebaseapp.com',
    storageBucket: 'codeelan-b4a49.appspot.com',
    measurementId: 'G-7LBQXPS9Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSg8oewSAvAGI-A1HgF_-RYmfnEI-RtqA',
    appId: '1:126285085607:android:62a266135576dc3c1d5482',
    messagingSenderId: '126285085607',
    projectId: 'codeelan-b4a49',
    storageBucket: 'codeelan-b4a49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJKgj5MjRG51u2qaun1aRCvcV71hsLAIg',
    appId: '1:126285085607:ios:4979c361cc4bcb671d5482',
    messagingSenderId: '126285085607',
    projectId: 'codeelan-b4a49',
    storageBucket: 'codeelan-b4a49.appspot.com',
    iosBundleId: 'com.example.codeelan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJKgj5MjRG51u2qaun1aRCvcV71hsLAIg',
    appId: '1:126285085607:ios:4979c361cc4bcb671d5482',
    messagingSenderId: '126285085607',
    projectId: 'codeelan-b4a49',
    storageBucket: 'codeelan-b4a49.appspot.com',
    iosBundleId: 'com.example.codeelan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO0h_5Wc_wY7Ho2Qvl0c8bz0fDC4lL0II',
    appId: '1:126285085607:web:598ec78b41d989801d5482',
    messagingSenderId: '126285085607',
    projectId: 'codeelan-b4a49',
    authDomain: 'codeelan-b4a49.firebaseapp.com',
    storageBucket: 'codeelan-b4a49.appspot.com',
    measurementId: 'G-JBRQMMLWNR',
  );

}